### ISSUE TITLE
Переход с дополнения Asynclib на Threading

### ISSUE THREAD

**Issue by metroyanno** [evgfilim1/itcat_carmabot#20]

**Comment by evgfilim1** [comment]
@metroyanno А смысл, если всё и так работает нормально?

**Comment by metroyanno** [comment]
У Threading пакета лучше обрабатываются перменные, всё быстрее, и доступно в 10 раз больше потоков

**Comment by metroyanno** [comment]
И главный плюс - работает с Python 2.7 и для него ничего устанавливать не нужно

**Comment by evgfilim1** [comment]
@metroyanno Те, кто используют Python 2.7, пусть идут лесом. Я не собираюсь переписывать свой код на старый Python. А разницы между Threading и Asynclib с технической точки зрения нет, т.к. Asynclib основан на базе Threading

**Comment by metroyanno** [comment]
Ахахахахах, ты читать не умеешь? "используют Python 2.7," - Значит работает с версии 2.7 до 3.5

**Comment by metroyanno** [comment]
И т.д.

**Comment by metroyanno** [comment]
Крч, работает с версии Python 2.7+

**Comment by evgfilim1** [comment]
@metroyanno Python2 и Python3 — разные. Не тупи!

**Comment by metroyanno** [comment]
Бля, он работает на двух версиях, не тупи!

**Comment by evgfilim1** [comment]
@metroyanno Ичо

**Comment by metroyanno** [comment]
Жди пулл крч говоря

**Comment by OctoNezd** [comment]
ХУЙ

**Comment by george-brony** [comment]
@OctoNezd Лол

**Comment by OctoNezd** [comment]
@OctoNezd #quotes

**Comment by OctoNezd** [comment]
@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd #quotes

Reply to this message to post a comment on GitHub.

**Comment by OctoNezd** [comment]
@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd #quotes

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

**Comment by OctoNezd** [comment]
@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd #quotes

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

**Comment by OctoNezd** [comment]
@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd 💬 New comment on itcat carmabot#20 Переход с дополнения Asynclib на Threading
by @OctoNezd (https://github.com/OctoNezd)

@OctoNezd #quotes

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

Reply to this message to post a comment on GitHub.

**Comment by evgfilim1** [comment]
> Жди пулл

@
Прошло 16 дней

**Comment by OctoNezd** [comment]
Ты же евген

**Comment by OctoNezd** [comment]
Евгей

**Comment by OctoNezd** [comment]
ыыы

**Comment by EgoruOfficial** [comment]
@OctoNezd писос про

**Comment by Rirush** [comment]
@OctoNezd ЫыЫ!

**Comment by EgoruOfficial** [comment]
@OctoNezd чтобы тебя ебать?

**Comment by EgoruOfficial** [comment]
@EgoruOfficial да

**Comment by evgfilim1** [comment]
Ееее, срач

**Comment by Rirush** [comment]
@evgfilim1 Це не срач, це тест бота.

**Comment by evgfilim1** [comment]
Ща обсуждение залочу :laughing:

**Comment by evgfilim1** [comment]
@evgfilim1 Зачем
